### ISSUE TITLE
ADM is dead already by now.

### ISSUE THREAD

**Issue by arkarwmh** [MicrosoftTranslator/NodeJs-Example#3]
What and how am i supposed to fill-in the "azureDataMarketClientId" and "azureDataMarketClientSecret" tokens since the ADM has been shutdown.

**Comment by nonsequitir** [comment]
Well it was announced that this would be happening a number of months back.  All you need to do is go to the Cognitive services on Azure and create a new API key.  This is fully described on Microsoft's web page in step-by-step detail.

**Comment by awong1900** [comment]
@arkarwmh see pull request, some good guys have fixed it. 
@pierregreborio you should be merge it.

**Comment by cpoulain** [comment]
Sample is updated with commit 9eac7b3199fbefa9866b2bae9dbdcf5d5e23a74e.
